services:
  - docker

jobs:
  include:
    - stage: ansible-test
      language: python
      script:
        - pip install ansible
        - make update-props-dryrun
    - stage: unit
      language: java
      script:
        - export MAVEN_OPTS="$MAVEN_OPTS -DinteractiveMode=false -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
        - make unit
